# ------ root_path/dataset_name ------
root_path: '/mnt/nas/moming/data/'


# ------ Load Cache and Features ------
#load_cache: False
#load_pre_feat: False
#
load_cache: True
load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [3, 3]
search_step: [300, 20]

init_beta: 1
init_alpha: 1.17


# ------ Basic Config ------
dataset: 'imagenet'
shots: 16 #16
backbone: 'ViT-B/16'

lr: 0.001
augment_epoch: 10
train_epoch: 20