# ------ root_path/dataset_name ------
root_path: '/home/moming/code/VITCLIP/%s2014_4_clip.tsv'


# ------ Load Cache and Features ------
load_cache: False
load_pre_feat: False

#load_cache: True
#load_pre_feat: True


# ------ Hyperparamters ------
search_hp: True
# search_hp: False

search_scale: [3, 3]
search_step: [300, 20]

init_beta: 1
init_alpha: 1


# ------ Basic Config ------
dataset: 'vqa'
shots: 16
backbone: 'ViT-B/16' #'ViT-B/16'

#lr: 0.001
lr: 0.001
augment_epoch: 10
train_epoch: 20
gpu: "cuda:0"
